spring:
  application:
    name: bank-global-config-service

  profiles:
    active: native # Профиль native необходимо включать для поддержки хранилища в локальной файловой системе

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/ # Фолдер, из которого загружаются конфигурации

server:
  port: 10000 # Порт, на котором будет запущен Cloud Config Server